// <auto-generated />
using System;
using AppBasquete.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AppBasquete.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20200927191459_CriadoTabelaJogador")]
    partial class CriadoTabelaJogador
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AppBasquete.Models.Jogador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Jogadores");
                });

            modelBuilder.Entity("AppBasquete.Models.Jogo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("JogadorId")
                        .HasColumnType("int");

                    b.Property<int>("MaximoTemporada")
                        .HasColumnType("int");

                    b.Property<int>("MinimoTemporada")
                        .HasColumnType("int");

                    b.Property<int>("Placar")
                        .HasColumnType("int");

                    b.Property<int>("QuebraRecordeMaximo")
                        .HasColumnType("int");

                    b.Property<int>("QuebraRecordeMinimo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JogadorId");

                    b.ToTable("Jogos");
                });

            modelBuilder.Entity("AppBasquete.Models.Jogo", b =>
                {
                    b.HasOne("AppBasquete.Models.Jogador", "Jogador")
                        .WithMany("Jogos")
                        .HasForeignKey("JogadorId");
                });
#pragma warning restore 612, 618
        }
    }
}
